### ISSUE TITLE
package.json is missing

### ISSUE THREAD

**Issue by D-Nice** [ensdomains/solsha1#1]
Can just manually get `hash-test-vectors` as prescribed in the package-lock file, but since the lock file is there, I'm assuming the package.json should be there too, to just do an npm install.

**Comment by D-Nice** [comment]
Added package.json in my fork which brings hmac: https://github.com/D-Nice/hmacsha1

**Comment by Arachnid** [comment]
Thanks! I'd happily accept a PR for a version that integrated HMAC into the base contract instead of a separate one.

I think you may have misdiagnosed the issue  with testrpc; it doesn't know or care about Solidity's memory management strategy.

**Comment by D-Nice** [comment]
Sounds good about the PR, just didn't know if you felt it was appropriate to include here as well. But one thing that put me off from a PR is the testrpc issue I encountered. So you're saying I can't depend on slot 0x40 in testrpc giving me the correct offset. 

Any better workarounds than what I did so it can be just one contract ideally?

**Comment by Arachnid** [comment]
I'm saying that I think you've misdiagnosed the issue: testrpc treats all memory identically, so am issue specifically with 0x40 is very unlikely.

**Comment by D-Nice** [comment]
Ok, I understand what you're trying to say, but it was odd, because it's specific to testrpc only (tried on Oraclize version of browser-solidity, and it was fine there). When I have time, I'll check again, but it's as if the freemem pointer was reset or wasn't taking the calldata into account. I'll see what the freemem pointer is in the browser-solidity jvm and then in testrpc at the same point.

It would only fail apparently, when the key length was greater than block size, which would require an initial call to the sha1 function. I have a feeling that may cause some side effects in testrpc's memory after it returns. Unfortunately my experience with testrpc isn't great, we come across issues specific to it only all the time, and that's using the latest.

**Comment by D-Nice** [comment]
Seems it wasn't a testrpc issue, but in fact a side-effect in the caller's memory happening which I wasn't expecting.
